services:
  - name: GAuth Proxy
    description: A service that stands in front of Meetup Admin and handles Google OAuth authentication
    lifecycle: active
    awsAccount: "212646169882"
    tags:
      owner: revenue-guardians
    pipelines:
      - type: travis
        name: Travis CI
        link: https://travis-ci.org/github/meetup/gauth-proxy
    logs:
      - type: cloudwatch
        name: CloudWatch Insights
        link: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E0$257Estart$257E-3600$257EtimeType$257E$2527RELATIVE$257Eunit$257E$2527seconds$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020$257EisLiveTail$257Efalse$257EqueryId$257E$252783ecc423-9976-44d6-a9b2-4115b3982135$257Esource$257E$2528$257E$2527*2fmeetup*2fprod*2fgauth-proxy-prod*2fgauth-proxy$2529$2529
